/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FoodItem, UserAddress, OrderHistoryItem, AppNotification } from './types';

export const FOOD_ITEMS: FoodItem[] = [
  {
    id: 't1',
    name: 'Ghee Masala Dosa',
    nameTelugu: 'నెయ్యి మసాలా దోస',
    category: 'tiffins',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    deliveryTime: 15,
    price: 110,
    calories: 380,
    protein: '7g',
    carbs: '54g',
    fat: '14g',
    ingredients: ['Rice batter', 'Pure ghee', 'Potato masal', 'Chutney', 'Sambar'],
    ingredientsTelugu: ['బియ్యం పిండి', 'స్వచ్ఛమైన నెయ్యి', 'ఆలు మసాలా', 'చట్నీ', 'సాంబార్'],
    healthIndicator: 'yellow',
    description: 'Golden, crispy hand-rolled rice crepe basted with pure hand-churned aromatic ghee and stuffed with dry spicy potato smash.',
    descriptionTelugu: 'స్వచ్ఛమైన నెయ్యి మరియు రుచికరమైన బంగాళాదుంప మసాలాతో తయారు చేసిన గరిటె లాంటి కరకరలాడే రుచికరమైన దోస.',
    popular: true,
    healthy: false,
    quick: true
  },
  {
    id: 't2',
    name: 'Butter Steamed Idli',
    nameTelugu: 'వెన్న ఆవిరి ఇడ్లీ',
    category: 'tiffins',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    deliveryTime: 10,
    price: 80,
    calories: 220,
    protein: '6g',
    carbs: '42g',
    fat: '3g',
    ingredients: ['Fermented black lentils', 'Rice rava', 'White butter', 'Peanut chutney'],
    ingredientsTelugu: ['మినపప్పు', 'వరి రవ్వ', 'తెల్ల వెన్న', 'పల్లీ చట్నీ'],
    healthIndicator: 'green',
    description: 'Fluffy cloud-like steamed rice cakes served hot with a dollop of white farm butter, spiced lentil powder (podi) and fresh peanut chutney.',
    descriptionTelugu: 'ఆవిరి మీద ఉడికించిన మెత్తటి ఇడ్లీలు, వెన్న, కారప్పొడి మరియు తాజా చట్నీతో వడ్డించబడును.',
    popular: true,
    healthy: true,
    quick: true
  },
  {
    id: 'm1',
    name: 'Royal Hyderabadi Biryani',
    nameTelugu: 'షాహీ హైదరాబాదీ బిర్యానీ',
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    deliveryTime: 25,
    price: 290,
    calories: 780,
    protein: '28g',
    carbs: '85g',
    fat: '32g',
    ingredients: ['Basmati rice', 'Saffron', 'Spiced chicken marinated with curd', 'Biryani gravy', 'Mirchi ka Salan'],
    ingredientsTelugu: ['బాస్మతి బియ్యం', 'కుంకుమపువ్వు', 'మసాలా చికెన్', 'బిర్యానీ గ్రేవీ', 'మిర్చి కా సలాన్'],
    healthIndicator: 'red',
    description: 'Long-grain fragrant basmati rice masterfully layered with marinated premium chicken pieces, cooked under high dum pressure with saffron threads.',
    descriptionTelugu: 'సువాసనగల బాస్మతి బియ్యం, మసాలాలతో నానబెట్టిన ముక్కలు మరియు కుంకుమపువ్వుతో దమ్ చేసిన ప్రామాణికమైన షాహీ బిర్యానీ.',
    popular: true,
    healthy: false,
    quick: false
  },
  {
    id: 'm2',
    name: 'Cozy Deluxe South Thali',
    nameTelugu: 'దక్షిణ భారతీయ భోజనం',
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    deliveryTime: 20,
    price: 180,
    calories: 610,
    protein: '14g',
    carbs: '95g',
    fat: '11g',
    ingredients: ['Steamed rice', 'Dal fry', 'Curd', 'Avakaya pickle', 'Papad', 'Payasam'],
    ingredientsTelugu: ['అన్నం', 'పప్పు', 'పెరుగు', 'ఆవకాయ పచ్చడి', 'అప్పడం', 'పాయసం'],
    healthIndicator: 'green',
    description: 'An emotionally comforting, home-style platter with pure ghee rice, warm lentil soup (pappu), spicy mango pickle, rasam, and classic sweet payasam.',
    descriptionTelugu: 'ఆవకాయ పచ్చడి, నెయ్యి పప్పు, వేడి అన్నం, చారు మరియు తియ్యటి పాయసంతో కూడిన సంపూర్ణమైన సాంప్రదాయ భోజనం.',
    popular: false,
    healthy: true,
    quick: false
  },
  {
    id: 'f1',
    name: 'Golden Double Cheese Burger',
    nameTelugu: 'డబుల్ చీజ్ బర్గర్',
    category: 'fastfood',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    deliveryTime: 12,
    price: 150,
    calories: 540,
    protein: '22g',
    carbs: '48g',
    fat: '24g',
    ingredients: ['Artisanal sesame bun', 'Vibrant cheddar cheese layers', 'Fresh lettuce', 'Cyra special smoke sauce'],
    ingredientsTelugu: ['నువ్వుల బన్', 'చెడ్డార్ చీజ్ పొరలు', 'తాజా లెట్యూస్', 'సైరా స్పెషల్ సాస్'],
    healthIndicator: 'red',
    description: 'Thick, ultra-juicy flame-grilled homemade patty covered in dual layers of rich melting golden cheddar inside toasted buttered buns.',
    descriptionTelugu: 'రెండు పొరల కరిగిన జున్ను మరియు తాజా ఆకుకూరలతో కూడిన నోరూరించే జ్యుసి డబుల్ చీజ్ బర్గర్.',
    popular: true,
    healthy: false,
    quick: true
  },
  {
    id: 'f2',
    name: 'Gourmet Bella Pizza',
    nameTelugu: 'గౌర్మెట్ బెల్లా పిజ్జా',
    category: 'fastfood',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    deliveryTime: 18,
    price: 240,
    calories: 690,
    protein: '19g',
    carbs: '76g',
    fat: '19g',
    ingredients: ['Sourdough crust', 'San Marzano tomato base', 'Bocconcini mozzarella', 'Fresh basil'],
    ingredientsTelugu: ['గోధుమ పిజ్జా బేస్', 'టమోటా సాస్', 'మొజారెల్లా చీజ్', 'తులసి ఆకులు'],
    healthIndicator: 'yellow',
    description: 'Freshly stretched fluffy sourdough crust topped with chunky signature sweet tomato pulp, fresh Italian mozzarella balls, and aromatic garden sweet basil.',
    descriptionTelugu: 'తాజా తులసి ఆకులు, వేడి టమోటా సాస్ మరియు కరిగిన మొజారెల్లా జున్నుతో కాల్చిన అద్భుతమైన ఇటాలియన్ పిజ్జా.',
    popular: false,
    healthy: false,
    quick: false
  },
  {
    id: 'd1',
    name: 'Blissful Mango Lassi',
    nameTelugu: 'మ్యాంగో లస్సీ',
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    deliveryTime: 8,
    price: 90,
    calories: 180,
    protein: '4g',
    carbs: '30g',
    fat: '2g',
    ingredients: ['Alphonso mango pulp', 'Thick organic yogurt', 'Cardamom zest', 'Slivered almonds'],
    ingredientsTelugu: ['అల్ఫోన్సో మామిడి గుజ్జు', 'చిక్కని పెరుగు', 'యాలకుల పొడి', 'బాదం పలుకులు'],
    healthIndicator: 'green',
    description: 'Chilled creamed sweet yogurt base blended smoothly with premium handpicked ripe sweet mangoes and topped with aromatic crushed cardamoms.',
    descriptionTelugu: 'తాజా మామిడి మరియు చిక్కని పెరుగుతో కలగలిపిన చల్లని తియ్యటి లస్సీ, పైన బాదం పలుకులతో అలంకరించబడును.',
    popular: true,
    healthy: true,
    quick: true
  },
  {
    id: 'd2',
    name: 'Cool Lemon Matcha Infusion',
    nameTelugu: 'లెమన్ గ్రీన్ టీ',
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    deliveryTime: 7,
    price: 110,
    calories: 95,
    protein: '1g',
    carbs: '22g',
    fat: '0g',
    ingredients: ['Ceremonial Kyoto matcha', 'Squeezed Persian lime', 'Chilled ice flakes', 'Organic raw honey'],
    ingredientsTelugu: ['గ్రీన్ టీ పౌడర్', 'తాజా నిమ్మరసం', 'మంచు ముక్కలు', 'తేనె'],
    healthIndicator: 'green',
    description: 'Vibrant ceremony-grade antioxidant-rich green matcha whisked cold with raw pure wild honey, and a bright splash of freshly squeezed lime juice.',
    descriptionTelugu: 'ఆరోగ్యకరమైన గ్రీన్ టీ మరియు తాజా నిమ్మరసంతో చేసిన చల్లని ఎనర్జీ డ్రింక్.',
    popular: false,
    healthy: true,
    quick: true
  },
  {
    id: 'de1',
    name: 'Warm Choco Lava Volcano',
    nameTelugu: 'చాకో లావా కేక్',
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    deliveryTime: 12,
    price: 130,
    calories: 450,
    protein: '5g',
    carbs: '55g',
    fat: '22g',
    ingredients: ['Premium Belgian dark cocoa', 'Unsalted cream butter', 'Organic cane sugar', 'Liquid ganache core'],
    ingredientsTelugu: ['డార్క్ చాక్లెట్ కోకో', 'వెన్న', 'చక్కెర', 'కరిగిన చాక్లెట్ గుండె'],
    healthIndicator: 'red',
    description: 'Warm, soft-baked chocolate souffle featuring a magical liquid hot fudge ganache core that flows out as soon as your spoon breaks the surface.',
    descriptionTelugu: 'నోట్లో వేస్తే కరిగిపోయే వేడి చాక్లెట్ నిండిన అద్భుతమైన చాకో లావా కేక్.',
    popular: true,
    healthy: false,
    quick: true
  },
  {
    id: 'de2',
    name: 'Delicate Berry Velvet Pastry',
    nameTelugu: 'బెర్రీ వెల్వెట్ పేస్ట్రీ',
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    deliveryTime: 10,
    price: 140,
    calories: 340,
    protein: '4g',
    carbs: '42g',
    fat: '16g',
    ingredients: ['Light buttermilk layers', 'Madagascar vanilla bean whip', 'Organic raspberry compote'],
    ingredientsTelugu: ['వెల్వెట్ కేక్ పొరలు', 'వెనిల్లా విప్డ్ క్రీమ్', 'రాస్ప్‌బెర్రీ పండ్లు'],
    healthIndicator: 'yellow',
    description: 'Layers of moist vanilla velvet pastry laced with tart sweet freshly extracted mountain forest raspberry reduction and premium light butter whip.',
    descriptionTelugu: 'తాజా రాస్ప్‌బెర్రీ బెర్రీలు మరియు వెనిల్లా క్రీమ్‌తో చేసిన మృదువైన వెల్వెట్ కేక్ ముక్క.',
    popular: false,
    healthy: false,
    quick: true
  },
  {
    id: 't3',
    name: 'Andhra Pesarattu Upma',
    nameTelugu: 'పెసరట్టు ఉప్మా',
    category: 'tiffins',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    deliveryTime: 12,
    price: 120,
    calories: 410,
    protein: '11g',
    carbs: '58g',
    fat: '12g',
    ingredients: ['Green gram', 'Ginger chutney', 'Semolina upma', 'Ghee'],
    ingredientsTelugu: ['పెసరపప్పు', 'అల్లం చట్నీ', 'ఉప్మా', 'నెయ్యి'],
    healthIndicator: 'green',
    description: 'Crisp nutritious whole green gram crepe stuffed with smooth spiced ginger semolina and loaded with pure ghee.',
    descriptionTelugu: 'తాజా అల్లం చట్నీ మరియు వేడి నెయ్యి ఉప్మాతో నిండిన ఆరోగ్యకరమైన పెసరట్టు.',
    popular: true,
    healthy: true,
    quick: true
  },
  {
    id: 'm3',
    name: 'Paneer Butter Masala Thali',
    nameTelugu: 'పనీర్ బటర్ మసాలా థాలి',
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    deliveryTime: 20,
    price: 240,
    calories: 720,
    protein: '19g',
    carbs: '80g',
    fat: '29g',
    ingredients: ['Fresh Paneer', 'Butter cream gravy', 'Tandoori Roti', 'Jeera Rice'],
    ingredientsTelugu: ['తాజా పనీర్', 'వెన్న గ్రేవీ', 'రోటి', 'జీరా రైస్'],
    healthIndicator: 'yellow',
    description: 'Soft cottage cheese cubes cooked in rich tomato butter gravy, served alongside fluffy jeera rice and toasted rotis.',
    descriptionTelugu: 'వెన్న గ్రేవీలో వండిన పనీర్ కూర, జీరా రైస్ మరియు వేడి రోటీలతో కూడిన రుచికరమైన భోజనం.',
    popular: true,
    healthy: false,
    quick: false
  },
  {
    id: 'f3',
    name: 'Spicy Paneer Wrap',
    nameTelugu: 'పనీర్ రోల్',
    category: 'fastfood',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    deliveryTime: 12,
    price: 130,
    calories: 460,
    protein: '15g',
    carbs: '42g',
    fat: '18g',
    ingredients: ['Tortilla', 'Grilled cottage cheese', 'Chone sauce', 'Peppers'],
    ingredientsTelugu: ['రోల్ చపాతీ', 'గ్రిల్డ్ పనీర్', 'స్పైసీ సాస్', 'క్యాప్సికం'],
    healthIndicator: 'yellow',
    description: 'Fresh wheat wrap loaded with grilled paneer blocks, crunchy sweet bell peppers, and chef special chili-mint drizzle.',
    descriptionTelugu: 'తాజా పనీర్ ముక్కలు మరియు క్యాప్సికంతో చుట్టిన నోరూరించే స్పైసీ పనీర్ రోల్.',
    popular: false,
    healthy: true,
    quick: true
  },
  {
    id: 'd3',
    name: 'Cozy Badam Milk Shard',
    nameTelugu: 'బాదం పాలు',
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    deliveryTime: 5,
    price: 70,
    calories: 190,
    protein: '5g',
    carbs: '24g',
    fat: '6g',
    ingredients: ['Chilled milk', 'Shredded almonds', 'Saffron stamen', 'Honey'],
    ingredientsTelugu: ['చిక్కని పాలు', 'బాదం పలుకులు', 'కుంకుమపువ్వు', 'తేనె'],
    healthIndicator: 'green',
    description: 'Rich chilled creamy milk infused with grounded sweet almonds, cardamom, real saffron strands, and crushed nuts.',
    descriptionTelugu: 'కుంకుమపువ్వు మరియు బాదం పప్పులతో తయారైన చల్లని పోషకదాయకమైన స్వచ్ఛమైన బాదం పాలు.',
    popular: true,
    healthy: true,
    quick: true
  },
  {
    id: 'de3',
    name: 'Qubani Ka Meetha Apricot',
    nameTelugu: 'ఖుబానీ కా మీఠా',
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    deliveryTime: 10,
    price: 160,
    calories: 390,
    protein: '3g',
    carbs: '65g',
    fat: '8g',
    ingredients: ['Dried apricots', 'Sugar syrup', 'Almond kernels', 'Vanilla ice cream scoop'],
    ingredientsTelugu: ['ఆప్రికాట్ పండ్లు', 'చక్కెర పాకం', 'బాదం పలుకులు', 'వెనిల్లా ఐస్ క్రీమ్'],
    healthIndicator: 'yellow',
    description: 'A legendary sweet made from stewed dried apricots, generously served with fresh milk cream or vanilla ice cream.',
    descriptionTelugu: 'హైదరాబాదీ స్పెషల్ ఎండు ఆప్రికాట్ పండ్ల తీపి వంటకం, పైన వెనిల్లా ఐస్ క్రీమ్‌తో వడ్డించబడును.',
    popular: true,
    healthy: false,
    quick: true
  }
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    timeLabel: '7:00 AM',
    message: 'Good morning 🌞 Your breakfast is waiting 🥞',
    messageTelugu: 'శుభోదయం 🌞 మీ వేడి అల్పాహారం సిద్ధంగా ఉంది 🥞',
    icon: '🥞',
    type: 'breakfast'
  },
  {
    id: 'n2',
    timeLabel: '12:00 PM',
    message: 'Lunch time 🍛 Eat well and stay happy 💛',
    messageTelugu: 'మధ్యాహ్న భోజన సమయం 🍛 చక్కగా తిని సంతోషంగా ఉండండి 💛',
    icon: '🍛',
    type: 'lunch'
  },
  {
    id: 'n3',
    timeLabel: '7:00 PM',
    message: 'Dinner alert 🌙 Warm food, peaceful mood 🍲',
    messageTelugu: 'రాత్రి భోజన సమయం 🌙 వేడి ఆహారం, ప్రశాంతమైన మనసు 🍲',
    icon: '🍲',
    type: 'dinner'
  },
  {
    id: 'n4',
    timeLabel: '2:30 PM',
    message: 'Your stomach called us 📞 Quick bites incoming!',
    messageTelugu: 'మీ పొట్ట మాకు ఫోన్ చేసింది 📞 త్వరగా ఏదో ఒకటి ఆర్డర్ చేయండి!',
    icon: '📞',
    type: 'alert'
  },
  {
    id: 'n5',
    timeLabel: '5:00 PM',
    message: 'Tiny cravings deserve big happiness 🍕 Order snacks now!',
    messageTelugu: 'చిన్న ఆకలి కూడా పెద్ద సంతోషాన్ని ఇవ్వాలి 🍕 స్నాక్స్ ఆర్డర్ చేయండి!',
    icon: '🍕',
    type: 'cravings'
  },
  {
    id: 'n6',
    timeLabel: '9:00 PM',
    message: 'Hungry humans need tasty hugs 🍔 Let us deliver snug comfort.',
    messageTelugu: 'ఆకలితో ఉన్న మనసులకు రుచికరమైన కౌగిలి అవసరం 🍔 కడుపు నింపుకోండి.',
    icon: '🍔',
    type: 'hugs'
  }
];

export const SAVED_ADDRESSES: UserAddress[] = [];

export const INITIAL_ORDER_HISTORY: OrderHistoryItem[] = [
  {
    id: 'CY-8921',
    date: '22 May 2026',
    foodName: 'Ghee Masala Dosa',
    amount: 220,
    status: 'Delivered'
  },
  {
    id: 'CY-8802',
    date: '19 May 2026',
    foodName: 'Royal Hyderabadi Biryani',
    amount: 320,
    status: 'Delivered'
  },
  {
    id: 'CY-8199',
    date: '10 May 2026',
    foodName: 'Blissful Mango Lassi',
    amount: 180,
    status: 'Delivered'
  }
];
